### ISSUE TITLE
Lisette doesn't emit imports sometimes, breaks "learn-lisette/store"

### ISSUE THREAD

**Issue by zapu** [ivov/lisette#408]
On a fresh `lis learn` project:
```
$ lis version
lis 0.2.4 (go 1.25.10)
$ rm -r target && lis run
# learn-lisette/store
store/store.go:11:18: undefined: os
store/store.go:23:11: undefined: json
store/store.go:38:18: undefined: json
store/store.go:48:11: undefined: os
store/store.go:48:55: undefined: fs
```

I bisected it to commit:
```
commit c738613d6acc63c5c65c3cc4906bbcc4d26dd857 (HEAD)
Author: Iván Ovejero <ivov.src@gmail.com>
Date:   Tue May 12 04:35:12 2026 +0200

    fix: solve more emit edge cases (#396)
```

Seems to be "magically" fixed after I replace all `doesn't` with `doesnt` in `learn-lisette/src/store/store.lis`. But I don't know why, it was something I tried because I saw a function in the diff that deals with skipping over string literals (I don't even know enough rust to fully understand it).

Thanks!

**Comment by ivov** [comment]
Thank you for taking the time to report! And for the investigation. I'll find a better approach for this. Addressing soon.
